// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// FFI bindings for the native add library functions.
class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup) : _lookup = lookup;

  int add(
    int a,
    int b,
  ) {
    return _add(
      a,
      b,
    );
  }

  late final _addPtr = _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int32, ffi.Int32)>>('add');
  late final _add = _addPtr.asFunction<int Function(int, int)>();

  void fibo(
    int n,
    ffi.Pointer<ffi.Int32> result,
  ) {
    return _fibo(
      n,
      result,
    );
  }

  late final _fiboPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int32, ffi.Pointer<ffi.Int32>)>>('fibo');
  late final _fibo = _fiboPtr.asFunction<void Function(int, ffi.Pointer<ffi.Int32>)>();

  void fibo_batch(
    int n,
    int iterations,
    ffi.Pointer<ffi.Int32> results,
  ) {
    return _fibo_batch(
      n,
      iterations,
      results,
    );
  }

  late final _fibo_batchPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int32, ffi.Int32, ffi.Pointer<ffi.Int32>)>>('fibo_batch');
  late final _fibo_batch = _fibo_batchPtr.asFunction<void Function(int, int, ffi.Pointer<ffi.Int32>)>();

  int factorial(
    int n,
  ) {
    return _factorial(
      n,
    );
  }

  late final _factorialPtr = _lookup<ffi.NativeFunction<ffi.Int64 Function(ffi.Int32)>>('factorial');
  late final _factorial = _factorialPtr.asFunction<int Function(int)>();

  void factorial_batch(
    int n,
    int iterations,
    ffi.Pointer<ffi.Int64> results,
  ) {
    return _factorial_batch(
      n,
      iterations,
      results,
    );
  }

  late final _factorial_batchPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int32, ffi.Int32, ffi.Pointer<ffi.Int64>)>>('factorial_batch');
  late final _factorial_batch = _factorial_batchPtr.asFunction<void Function(int, int, ffi.Pointer<ffi.Int64>)>();

  double monte_carlo_pi(
    int num_samples,
  ) {
    return _monte_carlo_pi(
      num_samples,
    );
  }

  late final _monte_carlo_piPtr = _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Int64)>>('monte_carlo_pi');
  late final _monte_carlo_pi = _monte_carlo_piPtr.asFunction<double Function(int)>();

  void monte_carlo_pi_batch(
    int num_samples,
    int iterations,
    ffi.Pointer<ffi.Double> results,
  ) {
    return _monte_carlo_pi_batch(
      num_samples,
      iterations,
      results,
    );
  }

  late final _monte_carlo_pi_batchPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Int32, ffi.Pointer<ffi.Double>)>>('monte_carlo_pi_batch');
  late final _monte_carlo_pi_batch = _monte_carlo_pi_batchPtr.asFunction<void Function(int, int, ffi.Pointer<ffi.Double>)>();

  void matrix_multiply(
    int m,
    int k,
    int n,
    ffi.Pointer<ffi.Double> A,
    ffi.Pointer<ffi.Double> B,
    ffi.Pointer<ffi.Double> C,
  ) {
    return _matrix_multiply(
      m,
      k,
      n,
      A,
      B,
      C,
    );
  }

  late final _matrix_multiplyPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int32, ffi.Int32, ffi.Int32, ffi.Pointer<ffi.Double>, ffi.Pointer<ffi.Double>, ffi.Pointer<ffi.Double>)>>('matrix_multiply');
  late final _matrix_multiply = _matrix_multiplyPtr.asFunction<void Function(int, int, int, ffi.Pointer<ffi.Double>, ffi.Pointer<ffi.Double>, ffi.Pointer<ffi.Double>)>();

  void matrix_multiply_batch(
    int m,
    int k,
    int n,
    ffi.Pointer<ffi.Double> A,
    ffi.Pointer<ffi.Double> B,
    int iterations,
    ffi.Pointer<ffi.Double> results,
  ) {
    return _matrix_multiply_batch(
      m,
      k,
      n,
      A,
      B,
      iterations,
      results,
    );
  }

  late final _matrix_multiply_batchPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int32, ffi.Int32, ffi.Int32, ffi.Pointer<ffi.Double>, ffi.Pointer<ffi.Double>, ffi.Int32, ffi.Pointer<ffi.Double>)>>('matrix_multiply_batch');
  late final _matrix_multiply_batch = _matrix_multiply_batchPtr.asFunction<void Function(int, int, int, ffi.Pointer<ffi.Double>, ffi.Pointer<ffi.Double>, int, ffi.Pointer<ffi.Double>)>();
}

typedef int_least8_t = ffi.Int8;
typedef Dartint_least8_t = int;
typedef int_least16_t = ffi.Int16;
typedef Dartint_least16_t = int;
typedef int_least32_t = ffi.Int32;
typedef Dartint_least32_t = int;
typedef int_least64_t = ffi.Int64;
typedef Dartint_least64_t = int;
typedef uint_least8_t = ffi.Uint8;
typedef Dartuint_least8_t = int;
typedef uint_least16_t = ffi.Uint16;
typedef Dartuint_least16_t = int;
typedef uint_least32_t = ffi.Uint32;
typedef Dartuint_least32_t = int;
typedef uint_least64_t = ffi.Uint64;
typedef Dartuint_least64_t = int;
typedef int_fast8_t = ffi.Int8;
typedef Dartint_fast8_t = int;
typedef int_fast16_t = ffi.Int16;
typedef Dartint_fast16_t = int;
typedef int_fast32_t = ffi.Int32;
typedef Dartint_fast32_t = int;
typedef int_fast64_t = ffi.Int64;
typedef Dartint_fast64_t = int;
typedef uint_fast8_t = ffi.Uint8;
typedef Dartuint_fast8_t = int;
typedef uint_fast16_t = ffi.Uint16;
typedef Dartuint_fast16_t = int;
typedef uint_fast32_t = ffi.Uint32;
typedef Dartuint_fast32_t = int;
typedef uint_fast64_t = ffi.Uint64;
typedef Dartuint_fast64_t = int;
typedef __int8_t = ffi.SignedChar;
typedef Dart__int8_t = int;
typedef __uint8_t = ffi.UnsignedChar;
typedef Dart__uint8_t = int;
typedef __int16_t = ffi.Short;
typedef Dart__int16_t = int;
typedef __uint16_t = ffi.UnsignedShort;
typedef Dart__uint16_t = int;
typedef __int32_t = ffi.Int;
typedef Dart__int32_t = int;
typedef __uint32_t = ffi.UnsignedInt;
typedef Dart__uint32_t = int;
typedef __int64_t = ffi.LongLong;
typedef Dart__int64_t = int;
typedef __uint64_t = ffi.UnsignedLongLong;
typedef Dart__uint64_t = int;
typedef __darwin_intptr_t = ffi.Long;
typedef Dart__darwin_intptr_t = int;
typedef __darwin_natural_t = ffi.UnsignedInt;
typedef Dart__darwin_natural_t = int;
typedef __darwin_ct_rune_t = ffi.Int;
typedef Dart__darwin_ct_rune_t = int;

final class __mbstate_t extends ffi.Opaque {}

typedef __darwin_mbstate_t = __mbstate_t;
typedef __darwin_ptrdiff_t = ffi.Long;
typedef Dart__darwin_ptrdiff_t = int;
typedef __darwin_size_t = ffi.UnsignedLong;
typedef Dart__darwin_size_t = int;
typedef __builtin_va_list = ffi.Pointer<ffi.Char>;
typedef __darwin_va_list = __builtin_va_list;
typedef __darwin_wchar_t = ffi.Int;
typedef Dart__darwin_wchar_t = int;
typedef __darwin_rune_t = __darwin_wchar_t;
typedef __darwin_wint_t = ffi.Int;
typedef Dart__darwin_wint_t = int;
typedef __darwin_clock_t = ffi.UnsignedLong;
typedef Dart__darwin_clock_t = int;
typedef __darwin_socklen_t = __uint32_t;
typedef __darwin_ssize_t = ffi.Long;
typedef Dart__darwin_ssize_t = int;
typedef __darwin_time_t = ffi.Long;
typedef Dart__darwin_time_t = int;
typedef __darwin_blkcnt_t = __int64_t;
typedef __darwin_blksize_t = __int32_t;
typedef __darwin_dev_t = __int32_t;
typedef __darwin_fsblkcnt_t = ffi.UnsignedInt;
typedef Dart__darwin_fsblkcnt_t = int;
typedef __darwin_fsfilcnt_t = ffi.UnsignedInt;
typedef Dart__darwin_fsfilcnt_t = int;
typedef __darwin_gid_t = __uint32_t;
typedef __darwin_id_t = __uint32_t;
typedef __darwin_ino64_t = __uint64_t;
typedef __darwin_ino_t = __darwin_ino64_t;
typedef __darwin_mach_port_name_t = __darwin_natural_t;
typedef __darwin_mach_port_t = __darwin_mach_port_name_t;
typedef __darwin_mode_t = __uint16_t;
typedef __darwin_off_t = __int64_t;
typedef __darwin_pid_t = __int32_t;
typedef __darwin_sigset_t = __uint32_t;
typedef __darwin_suseconds_t = __int32_t;
typedef __darwin_uid_t = __uint32_t;
typedef __darwin_useconds_t = __uint32_t;

final class _opaque_pthread_attr_t extends ffi.Opaque {}

final class _opaque_pthread_cond_t extends ffi.Opaque {}

final class _opaque_pthread_condattr_t extends ffi.Opaque {}

final class _opaque_pthread_mutex_t extends ffi.Opaque {}

final class _opaque_pthread_mutexattr_t extends ffi.Opaque {}

final class _opaque_pthread_once_t extends ffi.Opaque {}

final class _opaque_pthread_rwlock_t extends ffi.Opaque {}

final class _opaque_pthread_rwlockattr_t extends ffi.Opaque {}

final class _opaque_pthread_t extends ffi.Opaque {}

typedef __darwin_pthread_attr_t = _opaque_pthread_attr_t;
typedef __darwin_pthread_cond_t = _opaque_pthread_cond_t;
typedef __darwin_pthread_condattr_t = _opaque_pthread_condattr_t;
typedef __darwin_pthread_key_t = ffi.UnsignedLong;
typedef Dart__darwin_pthread_key_t = int;
typedef __darwin_pthread_mutex_t = _opaque_pthread_mutex_t;
typedef __darwin_pthread_mutexattr_t = _opaque_pthread_mutexattr_t;
typedef __darwin_pthread_once_t = _opaque_pthread_once_t;
typedef __darwin_pthread_rwlock_t = _opaque_pthread_rwlock_t;
typedef __darwin_pthread_rwlockattr_t = _opaque_pthread_rwlockattr_t;
typedef __darwin_pthread_t = ffi.Pointer<_opaque_pthread_t>;
typedef intmax_t = ffi.Long;
typedef Dartintmax_t = int;
typedef uintmax_t = ffi.UnsignedLong;
typedef Dartuintmax_t = int;
