// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;
import 'dart:ffi';
import 'dart:io' show Platform;

final DynamicLibrary _lib = Platform.isMacOS
    ? DynamicLibrary.open('libnative_add.dylib')
    : Platform.isLinux
        ? DynamicLibrary.open('libnative_add.so')
        : DynamicLibrary.open('native_add.dll');

final ffi.Pointer<ffi.Int32> Function(int) fibo = _lib
    .lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int32> Function(ffi.Int32)>>('fibo')
    .asFunction();
